name: CI/CD Pipeline for msVehicles
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: MsVehicles
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 12345
        options: >-
          if pg_isready -h localhost -p 5432 -U admin -d MsVehicles; then
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 22  # Versión especificada en tu pom.xml
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Esperar a que Postgres esté listo
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U admin; then
              echo "Postgres está listo"
              break
            fi
            echo "Esperando a Postgres..."
            sleep 2
          done

      - name: Build and test with Maven
        run: |
          mvn clean package
          mvn test